language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      script:
        - cmake --version
        - mkdir ./build
        - cd ./build
        - cmake ..
        - make
